### ISSUE TITLE
Toga-Demo buttons raise an exception

### ISSUE THREAD

**Issue by stevemolloy** [pybee/toga#226]
Following the guide, I used pip to install toga-demo and then ran it.

Clicking on any of the buttons results in the following on the terminal:
```
button press
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/Users/stephenmolloy/PycharmProjects/toga_sandpit/venv3/lib/python3.6/site-packages/rubicon/objc/objc.py", line 863, in _objc_method
    result = f(py_self, *args)
  File "/Users/stephenmolloy/PycharmProjects/toga_sandpit/venv3/lib/python3.6/site-packages/toga_cocoa/utils.py", line 11, in performIteration_
    NSTimer.scheduledTimerWithTimeInterval_tarSEL_userInfo_repeats_(delay, self, SEL('performIteration:'), None, False)
  File "/Users/stephenmolloy/PycharmProjects/toga_sandpit/venv3/lib/python3.6/site-packages/rubicon/objc/objc.py", line 1139, in __getattr__
    raise AttributeError('%s.%s %s has no attribute %s' % (type(self).__module__, type(self).__qualname__, self.objc_class.name, name))
AttributeError: rubicon.objc.objc.ObjCClass NSTimer has no attribute scheduledTimerWithTimeInterval_tarSEL_userInfo_repeats_
```

This is Python3.6.0 on OS X 10.11.6
```
Python 3.6.0 (default, Dec 24 2016, 00:01:50) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by Ocupe** [comment]
This is a funny little bug that you found. The function `scheduledTimerWithTimeInterval_tarSEL_userInfo_repeats_` does not work because it should be named `scheduledTimerWithTimeInterval_target_selector_userInfo_repeats_`. The reason this bug was produced is because of a little coincident. There was a change in API and now we use `SEL()` instead of `get_selector()`. I guess when @freakboy3742 used the search and replace function to replace `get_selector` with `SEL()` the expression coincidently matched with the function name `scheduledTimerWithTimeInterval_tar**get_selector**_userInfo_repeats_` and you ended up with this bug. The reason why I know – I produced the same bug too :D.

@stevemolloy thank you for letting us know!

**Comment by Ocupe** [comment]
Fix is here https://github.com/pybee/toga/pull/227

@freakboy3742 This Issue can be closed.

**Comment by freakboy3742** [comment]
Thanks for the report @stevemolloy!

**Comment by samredway** [comment]
This is fixed in the repo but is still present when you pip install toga-demo. Has the fix been deployed?

**Comment by Ocupe** [comment]
@samredway Unfortunately no, it will be with the next version. But you can still use the newest version if you clone the repo from github.
