### ISSUE TITLE
Layout editor for toga, just like android studio

### ISSUE THREAD

**Issue by vishwas78** [pybee/toga#351]
## Expected Behavior

Just use drag and drop to create your widget in a predefined way, define its behavior yourself. Just like the android studio.

## Current Behavior

We have to code each and every part of the program. With this, we will be able to avoid the GUI part to some extent.

This is just an idea. Would love to hear your views on this and plan and work accordingly.

**Comment by freakboy3742** [comment]
Definitely an interesting idea; however, it's a bit premature. It would be a bit like someone launching their first model rocket, and then going to the store to pick carpet patterns for their Mars base :-)

A graphical editor for GUI layouts is definitely on the long term todo list, but getting the basics - like a good spread of widgets - working first -  is the immediate priority.

Closing this ticket because there's nothing immediately actionable here.

**Comment by vishwas78** [comment]
Yeah, you are right.

**Comment by albertz** [comment]
I wonder if there is any update on this?

**Comment by mhsmith** [comment]
Not at the moment, sorry. But if anyone was to create such a tool, we'd certainly consider accepting it as an official BeeWare project.
