### ISSUE TITLE
Recommend to install pygobject from pip

### ISSUE THREAD

**Issue by SanketDG** [pybee/toga#371]
I apologize to override the default template, but I don't think its applicable for this issue.

pygobject has been available from `pip` for a while now, and is always at the latest stable release.

Distro package managers are generally a little slow in getting packages updated (in this case its just a 3 months older release for Fedora)

`pip` on the other hand always has the latest version, and is great for people who use virtualenvs, since you have to do some ugly linking to get the system pygobject on the virtualenv

It also removes the intent to have code like this https://github.com/pybee/toga/blob/master/src/gtk/toga_gtk/app.py#L22

This code suggested me to use `pacman` to install pygobject on Fedora (might throw off beginners)

**Comment by freakboy3742** [comment]
Most users wont actually need to run pacman - the whole point of Toga is to use the system graphics libraries, and pygobject *should* be installed if you've got a graphical desktop. 

However, your point is valid - it would be vastly preferable to use PyPI, rather than the nasty symlink hack.

The reason we haven't done this historically is that PyGObject was only recently packaged in a way that it *could* be installed from PyPI. If you look at the history for the package, only the 3.27 series has been released to PyPI. That means this approach has only been possible for a little over 2 months.

If you'd like to submit a patch that modifies the Toga GTK backend to use a pip-installable PyGObject, it would definitely be merged.

**Comment by SanketDG** [comment]
> That means this approach has only been possible for a little over 2 months

Apologies for using the phrase "a while now" then. I have no idea how I made that connection.

I have opened a PR that removes most of the stuff. Let me know if it's okay/need changes.
