### ISSUE TITLE
Why toga.MultilineTextInput does not work?

### ISSUE THREAD

**Issue by tangshi** [pybee/toga#60]
I tried to write a `MultilineTextInput` demo, however nothing appeared

![2016-06-30 20 45 00](https://cloud.githubusercontent.com/assets/5255026/16488583/d3318078-3f03-11e6-9b2e-0e81be0353dc.png)

My platform: Mac OS X 10.11.5 

My code:

    import toga

    def build(app):
        container = toga.Container()
        msg = toga.MultilineTextInput('initialize')
        container.add(msg)
        container.constrain(msg.TOP == container.TOP + 50)
        container.constrain(msg.LEADING + 50 == container.LEADING)
        container.constrain(msg.TRAILING + 50 == container.TRAILING)
        container.constrain(msg.BOTTOM + 50 < container.BOTTOM)

        return container

    if __name__ == '__main__':
        app = toga.App('MultilineTextInput', 'com.identifier.app', startup=build)
        app.main_loop()

**Comment by elstob** [comment]
You're assigning your constraints incorrectly. The arithmetic should be on the right side of the == evaluation. Try this:

```python
import toga

def build(app):
    container = toga.Container()
    msg = toga.MultilineTextInput('initialize')
    container.add(msg)
    container.constrain(msg.TOP == container.TOP + 10)
    container.constrain(msg.LEADING == container.LEADING + 10)
    container.constrain(msg.TRAILING == container.TRAILING - 10)
    container.constrain(msg.BOTTOM == container.BOTTOM - 10)
    return container

if __name__ == '__main__':
    app = toga.App('My App', 'com.identifier.app', startup=build)
    app.main_loop()
```

**Comment by tangshi** [comment]
Thanks @elstob , but it works if I replace `<` with `==` whether the arithmetic is on the right or on the left.

However, the same constrains work with a `Button` ! what a confusing issue...

    def build(app):
        container = toga.Container()
        msg = toga.MultilineTextInput('initialize')
        container.add(msg)
        container.constrain(msg.TOP == container.TOP + 10)
        container.constrain(msg.TOP == container.TOP + 50)
        container.constrain(msg.LEADING == container.LEADING + 50)
        container.constrain(msg.TRAILING + 50 == container.TRAILING)
        container.constrain(msg.BOTTOM + 50 < container.BOTTOM)
        return container

    def build_btn(app):
        container = toga.Container()
        button = toga.Button('Hello world')
        container.add(button)
        container.constrain(button.TOP == container.TOP + 50)
        container.constrain(button.LEADING == container.LEADING + 50)
        container.constrain(button.TRAILING + 50 == container.TRAILING)
        container.constrain(button.BOTTOM + 50 < container.BOTTOM)
        return container

**Comment by freakboy3742** [comment]
@tangshi Sorry to hear you're having problems. It's entirely possible you're hitting a bug in Toga itself. There are some situations where Apple's default constraint rules kick in and override the behavior you've specified manually. Multiline text widgets are one of the most affected, because there are several underlying widgets involved.

It's because of problems like this one that I'm in the process of replacing the constraint-based layout system with a new approach based on CSS. Constraints are lovely... when they work. When they don't, they're almost impossible to debug. To make matters worse, there are some subtle differences in the implementation of Cassowary between platforms that make a consistent layout very difficult to coordinate.

You can see the work in progress on the "colosseum" branch of this repository; it's not quite ready for public use, but if you're feeling adventurous, you can experiment a bit.

**Comment by tangshi** [comment]
@freakboy3742 So sad, I just need a simple gui framework to create a demo

**Comment by freakboy3742** [comment]
@tangshi Totally understandable. Hopefully Toga will be able to fill that role in the near future.

I'll close this ticket on the basis that there's nothing specific that can be (or is going to be) addressed.
