### ISSUE TITLE
TypeError: 'ObjCInstance' object is not callable; Xcode required?

### ISSUE THREAD

**Issue by Code2Joke** [pybee/toga#602]
## Expected Behavior

I expected to see a GUI with the toga-demo

## Current Behavior

Traceback (most recent call last):
  File "/Users/patrick/miniconda3/bin/toga-demo", line 11, in <module>
    sys.exit(run())
  File "/Users/patrick/miniconda3/lib/python3.6/site-packages/toga_demo/__main__.py", line 5, in run
    main().main_loop()
  File "/Users/patrick/miniconda3/lib/python3.6/site-packages/toga_cocoa/app.py", line 167, in main_loop
    self._startup()
  File "/Users/patrick/miniconda3/lib/python3.6/site-packages/toga_cocoa/app.py", line 95, in _startup
    self._impl = NSApplication.sharedApplication()
TypeError: 'ObjCInstance' object is not callable

## Steps to reproduce

1. $ pip install toga-demo in home directory

2. $ toga-demo

* Python Version (list the specific version number)
Python 3.6

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)
  - [x] macOS - version: 10.14

* Toga Target (the type of app you are trying to generate)
  - [x] cocoa

**Comment by freakboy3742** [comment]
This is a problem that has been reported a few times (enough that it's even picked up by Google): 

https://github.com/pybee/toga/issues/154
https://github.com/pybee/toga/issues/243
https://github.com/pybee/toga/issues/322

The issue is that the "stable" 0.2.15 version of Toga won't currently work on High Sierra or later - you need to use the 0.3.0 development branch. Add `--pre` when you install toga-demo.
