### ISSUE TITLE
create navigation drawer

### ISSUE THREAD

**Issue by Brianzhengca** [pybee/toga#638]
is it possible to make a mobile app navigation drawer like this one using toga? This will be much easier for my users to navigate through my app and looks much neater
![image](https://user-images.githubusercontent.com/30914529/51584457-2ebd7880-1e8a-11e9-9962-89957a2825e9.png)

**Comment by Brianzhengca** [comment]
ok thank you!!!

**Comment by mhsmith** [comment]
Related: #785

**Comment by freakboy3742** [comment]
At least in my mind, this is a slightly different feature request. There's obviously some overlap (because the UX element appears in the titlebar), but a "NavigationController" to me is more about the "pushing a stack of views" for drilling into deep content. The "side drawer" is more of a top-level mechanism for system commands - more of an analog of the menu bar on a desktop app.

**Comment by johnzhou721** [comment]
I'd say this is more like a Sidebar structure... it's pretty common actually -- see, for example, the thing on the left in Finder on macOS:

<img width="954" height="892" alt="Image" src="https://github.com/user-attachments/assets/0e6673ec-b9dc-40a9-90bd-806cc453428b" />

For iPadOS there is a similar concept; for iOS Sidebars should be avoided per iOS HIG and only works in horizontal orientation.  For GNOME, Nautilus also has a sidebar.

However this should not be a widget, this is more like a "Window Structure" thing.  Windows with sidebars on macOS, Linux, and iPadOS all draws slightly differnetly at the root window structure than normal windows.  I don't know if Winforms has sidebar etc... but it seems that to make up for the API, we might need a splitview with a tree on the left.
